version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: normal
artifacts:
- path: '\bin\Release\PuttySessionBackup.exe'
  name: PuttySessionBackup
deploy:
- provider: GitHub
  auth_token:
    secure: TPlXMhslrtyd6OCCszlzELzf3dxDp56HTVxvirzDYoD6AyY25tqEAqVMCogu33Vq
  artifact: '*.exe'
  prerelease: true