version: 1.0.{build}
skip_tags: true
image:
- Ubuntu
- Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: PuttySessionBackup.sln
  publish_aspnet_core: true
  parallel: true
  verbosity: normal
before_deploy:
- cmd: dir
deploy:
- provider: GitHub
  auth_token:
    secure: TPlXMhslrtyd6OCCszlzELzf3dxDp56HTVxvirzDYoD6AyY25tqEAqVMCogu33Vq
  artifact: '**\PuttySessionBackup.exe'
  prerelease: true